### ISSUE TITLE
Dead kernel

### ISSUE THREAD

**Issue by NienkevandeLoosdrecht** [Alexander-Barth/HF-radar-assim-caen#1]
When I try to run the command lines of the exercise, I get the message: "the kernel appears to have died. It will restart automatically." But then nothing happens and if I retry it still doesn't work.

**Comment by nicolascouetard** [comment]
> When I try to run the command lines of the exercise, I get the message: "the kernel appears to have died. It will restart automatically." But then nothing happens and if I retry it still doesn't work.

Got the same problem, it seems to be related to julia 1.4.1 since this error message doesn't appear with the python 3 where the kernel is working.
_Under Linux Kubuntu 20.04_

**Comment by Alexander-Barth** [comment]
I use Ubuntu 20.04 too (gnome version). In the julia command line can you run the following (https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems):

```
ENV["IJULIA_DEBUG"]=true
using Pkg
Pkg.build("IJulia",verbose=true)
```

Can you paste the output of this previous command?

Then can you start `jupyter-notebook` from the terminal

```bash
jupyter-notebook  --debug assim_exercise.ipynb
```

or

```bash
/full/path/to/jupyter-notebook   --debug assim_exercise.ipynb
```
(by replacing `/full/path/to/` with the directory containing `jupyter-notebook`).

There might be some helpful error message in the terminal why the kernel is crashing.

**Comment by Alexander-Barth** [comment]
I just updated the instruction above to increase the number of messages. These commands will  (normally) generate a lot of screen output. Can you just copy paste them here.

**Comment by nicolascouetard** [comment]
> I use Ubuntu 20.04 too (gnome version). In the julia command line can you run the following (https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems):
> 
> ```
> ENV["IJULIA_DEBUG"]=true
> using Pkg
> Pkg.build("IJulia",verbose=true)
> ```
> 
> Can you paste the output of this previous command?
**I got:**
```
julia> ENV["IJULIA_DEBUG"]=true
true

julia> using Pkg

julia> Pkg.build("IJulia",verbose=true)
   Building Conda ─→ `~/.julia/packages/Conda/3rPhK/deps/build.log`
   Building IJulia → `~/.julia/packages/IJulia/DrVMH/deps/build.log`
[ Info: Installing Julia kernelspec in /home/ncouetard/.local/share/jupyter/kernels/julia-1.4
┌ Warning: JUPYTER=jupyter not found in PATH
└ @ Main ~/.julia/packages/IJulia/DrVMH/deps/build.jl:28"

```
> Then can you start `jupyter-notebook` from the terminal
> 
> ```shell
> jupyter-notebook  --debug assim_exercise.ipynb
> ```
> **For this I got:** 
```
(base) ncouetard@ncouetard-ZenBook-13-UX331UAL:~$ jupyter-notebook  --debug assim_exercise.ipynb
[C 22:45:23.404 NotebookApp] No such file or directory: /home/ncouetard/assim_exercise.ipynb
[D 22:45:23.404 NotebookApp] Exiting application: jupyter-notebook
```
> or
> 
> ```shell
> /full/path/to/jupyter-notebook   --debug assim_exercise.ipynb
> ```
**Since I've got 4 different "jupyter-notebook" in my personal directory, I replaced the path by all of them and I obtain:**

```
(base) ncouetard@ncouetard-ZenBook-13-UX331UAL:~$ /home/ncouetard/anaconda3/bin/jupyter-notebook   --debug assim_exercise.ipynb
[C 22:46:46.295 NotebookApp] No such file or directory: /home/ncouetard/assim_exercise.ipynb
[D 22:46:46.296 NotebookApp] Exiting application: jupyter-notebook
(base) ncouetard@ncouetard-ZenBook-13-UX331UAL:~$ /home/ncoueta…/envs/py3/bin/jupyter-notebook   --debug assim_exercise.ipynb
bash: /home/ncoueta…/envs/py3/bin/jupyter-notebook: Aucun fichier ou dossier de ce type
(base) ncouetard@ncouetard-ZenBook-13-UX331UAL:~$ /home/ncouetar…0.3-py37_0/bin/jupyter-notebook   --debug assim_exercise.ipynb
bash: /home/ncouetar…0.3-py37_0/bin/jupyter-notebook: Aucun fichier ou dossier de ce type
(base) ncouetard@ncouetard-ZenBook-13-UX331UAL:~$ /home/ncouetar…0.3-py38_0/bin/jupyter-notebook   --debug assim_exercise.ipynb
bash: /home/ncouetar…0.3-py38_0/bin/jupyter-notebook: Aucun fichier ou dossier de ce type
```

> 
> (by replacing `/full/path/to/` with the directory containing `jupyter-notebook`).
> 
> There might be some helpful error message in the terminal why the kernel is crashing.

**Comment by Alexander-Barth** [comment]
"Aucun fichier ou dossier de ce type": -> this is just that the file "assim_exercise.ipynb" is not yet downloaded. Can you decompress the files in this zip
https://github.com/Alexander-Barth/HF-radar-assim-exercise/archive/master.zip
`cd` into the folder where you should find a file `assim_exercise.ipynb`. 

It seems that you run these commands inside an activated conda environment (as you command line starts with `(base)`). I usually keep them separate.

Can you try this?
* `conda deactivate`: this will unload the conda environment and the `base` should disappear for the current terminal windows (this is not a permanent change)

Then can you send me the output of these 3 commands?

* `which python`
* `which python3`
* `which jupyter`

Then start julia and retype:

```julia
ENV["IJULIA_DEBUG"]=true
using Pkg
Pkg.build("IJulia",verbose=true)
using IJulia
IJulia.notebook()
```
After this in a separate terminal window, can you run the command `find ~ -name jupyter` and send me the output?

**Comment by nicolascouetard** [comment]
> "Aucun fichier ou dossier de ce type": -> this is just that the file "assim_exercise.ipynb" is not yet downloaded. Can you decompress the files in this zip
> https://github.com/Alexander-Barth/HF-radar-assim-exercise/archive/master.zip
> `cd` into the folder where you should find a file `assim_exercise.ipynb`.
> 
> It seems that you run these commands inside an activated conda environment (as you command line starts with `(base)`). I usually keep them separate.
> 
> Can you try this?
> 
>     * `conda deactivate`: this will unload the conda environment and the `base` should disappear for the current terminal windows (this is not a permanent change)
> 
> 
> Then can you send me the output of these 3 commands?
> 
>     * `which python`
```
ncouetard@ncouetard-ZenBook-13-UX331UAL:~$ which python
/usr/bin/python
```

>     * `which python3`
```
ncouetard@ncouetard-ZenBook-13-UX331UAL:~$ which python3
/usr/bin/python3
```
>     * `which jupyter`
`ncouetard@ncouetard-ZenBook-13-UX331UAL:~$ which jupyter`
**_Don't have any output for this line_**

> Then start julia and retype:
> 
> ```julia
> ENV["IJULIA_DEBUG"]=true
> using Pkg
> Pkg.build("IJulia",verbose=true)
> using IJulia
> IJulia.notebook()
> ```
> 
> After this in a separate terminal window, can you run the command `find ~ -name jupyter` and send me the output?

```
ncouetard@ncouetard-ZenBook-13-UX331UAL:~$ find ~ -name jupyter
/home/ncouetard/anaconda3/envs/py3/bin/jupyter
/home/ncouetard/anaconda3/envs/py3/etc/jupyter
/home/ncouetard/anaconda3/envs/py3/share/jupyter
/home/ncouetard/anaconda3/bin/jupyter
/home/ncouetard/anaconda3/etc/jupyter
/home/ncouetard/anaconda3/share/jupyter
/home/ncouetard/anaconda3/pkgs/_ipyw_jlab_nb_ext_conf-0.1.0-py37_0/etc/jupyter
/home/ncouetard/anaconda3/pkgs/jupyter_core-4.6.1-py37_0/bin/jupyter
/home/ncouetard/anaconda3/pkgs/widgetsnbextension-3.5.1-py37_0/etc/jupyter
/home/ncouetard/anaconda3/pkgs/widgetsnbextension-3.5.1-py37_0/share/jupyter
/home/ncouetard/anaconda3/pkgs/jupyter_core-4.6.3-py38_0/bin/jupyter
/home/ncouetard/anaconda3/pkgs/ipykernel-5.1.4-py37h39e3cac_0/share/jupyter
/home/ncouetard/anaconda3/pkgs/widgetsnbextension-3.5.1-py38_0/etc/jupyter
/home/ncouetard/anaconda3/pkgs/widgetsnbextension-3.5.1-py38_0/share/jupyter
/home/ncouetard/anaconda3/pkgs/r-irkernel-1.1-r36h6115d3f_1/share/jupyter
/home/ncouetard/anaconda3/pkgs/jupyterlab-1.2.6-pyhf63ae98_0/etc/jupyter
/home/ncouetard/anaconda3/pkgs/jupyterlab-1.2.6-pyhf63ae98_0/share/jupyter
/home/ncouetard/anaconda3/pkgs/ipykernel-5.1.4-py38h39e3cac_0/share/jupyter
/home/ncouetard/anaconda3/pkgs/r-irkernel-0.5-r3.2.2_1a/share/jupyter
/home/ncouetard/.julia/conda/3/bin/jupyter
/home/ncouetard/.julia/conda/3/etc/jupyter
/home/ncouetard/.julia/conda/3/share/jupyter
/home/ncouetard/.julia/conda/3/pkgs/widgetsnbextension-3.5.1-py37_0/etc/jupyter
/home/ncouetard/.julia/conda/3/pkgs/widgetsnbextension-3.5.1-py37_0/share/jupyter
/home/ncouetard/.julia/conda/3/pkgs/jupyter_core-4.6.3-py37_0/bin/jupyter
/home/ncouetard/.julia/conda/3/pkgs/ipykernel-5.1.4-py37h39e3cac_0/share/jupyter
/home/ncouetard/.local/share/jupyter

```

**Comment by Alexander-Barth** [comment]
OK, thanks. This look good so far. Can you try to go one step further and open the downloaded notebook following these steps?

* `conda deactivate`
* start julia and type
```julia
using IJulia
IJulia.notebook()
```
* a browser window should open with a notebook session
* In the notebook session, navigate to the folder containing `assim_exercise.ipynb` and open `assim_exercise.ipynb`
* Choose `run all` from the menu

If you see any errors can you paste them here?

**Comment by nicolascouetard** [comment]
It still doesn't work. It's written "connected to the kernel" but a few seconds after I got "the kernel appears to have died. It will restart automatically."

**Comment by Alexander-Barth** [comment]
As a last try, can you do these steps

* run `conda deactivate`
* `cd path` where `path` contains the downloaded notebooks
* run `/home/ncouetard/.julia/conda/3/bin/jupyter kernelspec list`
* run `/home/ncouetard/.julia/conda/3/bin/jupyter notebook --debug assim_exercise.ipynb`
* select `Cell` -> `Run all` in the notebook

Can you paste the output of the terminal and possible error message?

If this still does not work, please then I suggest you to use the binder service:

https://github.com/Alexander-Barth/HF-radar-assim-exercise#using-binder

**Comment by nicolascouetard** [comment]
```
ncouetard@ncouetard-ZenBook-13-UX331UAL:~$ cd /home/ncouetard/HF-radar-assim-exercise
ncouetard@ncouetard-ZenBook-13-UX331UAL:~/HF-radar-assim-exercise$ /home/ncouetard/.julia/conda/3/bin/jupyter kernelspec list
Available kernels:
  julia-1.4    /home/ncouetard/.local/share/jupyter/kernels/julia-1.4
  python3      /home/ncouetard/.julia/conda/3/share/jupyter/kernels/python3
```

```
ncouetard@ncouetard-ZenBook-13-UX331UAL:~/HF-radar-assim-exercise$ /home/ncouetard/.julia/conda/3/bin/jupyter --debug assim_exercise.ipynb
Traceback (most recent call last):
  File "/home/ncouetard/.julia/conda/3/bin/jupyter", line 11, in <module>
    sys.exit(main())
  File "/home/ncouetard/.julia/conda/3/lib/python3.7/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/home/ncouetard/.julia/conda/3/lib/python3.7/site-packages/jupyter_core/command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
```

I tried Binder and it works so I'll follow there. Thank you for having trying to solve my issue.

**Comment by mutiarizqydiani** [comment]
> I use Ubuntu 20.04 too (gnome version). In the julia command line can you run the following (https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems):
> 
> ```
> ENV["IJULIA_DEBUG"]=true
> using Pkg
> Pkg.build("IJulia",verbose=true)
> ```
> 
> Can you paste the output of this previous command?
> 
> Then can you start `jupyter-notebook` from the terminal
> 
> ```shell
> jupyter-notebook  --debug assim_exercise.ipynb
> ```
> 
> or
> 
> ```shell
> /full/path/to/jupyter-notebook   --debug assim_exercise.ipynb
> ```
> 
> (by replacing `/full/path/to/` with the directory containing `jupyter-notebook`).
> 
> There might be some helpful error message in the terminal why the kernel is crashing.

Does it apply for Windows? I have the same issue with the kernel and this method doesn't seem to be working for my computer

**Comment by Alexander-Barth** [comment]
I noticed a typo in my instructions. It should have been this (with the notebook)

```
/home/ncouetard/.julia/conda/3/bin/jupyter notebook --debug assim_exercise.ipynb
```
 
> I tried Binder and it works so I'll follow there. Thank you for having trying to solve my issue.

Yes, luckily there is binder that you can use. The caveat is that Binder will close your session after about 10 minutes. Let's try to keep the binder notebook busy during the lecture :-)

**Comment by Alexander-Barth** [comment]
@mutiarizqydiani , yes the instructions are essentially the same on windows (the path names are a bit different, /path/to/file becomes e.g. c:\path\to\file). 

A source of trouble can be an always activated conda environment (even if this seems not the be the issue of your colleague) or some outdated libraries in your system `Path`.

Here is how you see the `Path` variable in windows.
https://docs.telerik.com/teststudio/features/test-runners/add-path-environment-variables

It would be useful if you can paste the value of Path variable here.


You should not have a directory called miniconda, anaconda, ... there.

**Comment by NienkevandeLoosdrecht** [comment]
> @mutiarizqydiani , yes the instructions are essentially the same on windows (the path names are a bit different, /path/to/file becomes e.g. c:\path\to\file).
> 
> A source of trouble can be that you have an always activated conda environment (even if this seems not the be the issue of your colleague) or some outdated libraries in your system `Path`.
> 
> Here is how you see the `Path` variable in windows.
> https://docs.telerik.com/teststudio/features/test-runners/add-path-environment-variables
> 
> It would be useful if you can paste the value of Path variable here.
> 
> You should not have a directory called miniconda, anaconda, ... there.

I have a MacBook, is it the same?

**Comment by Alexander-Barth** [comment]
On a Mac (like Linux), you can get the content of the system PATH by open a terminal and type

```bash
echo $PATH
```

Check if  `jupyter` is already installed with

```bash
which  jupyter
```

Ideally, it should return nothing. In this case IJulia will install a "private" jupyter server.

A MacBook behaves essentially the same as Linux / Kubuntu 20.04.

**Comment by Alexander-Barth** [comment]
I just tried my instructions on a empty home directory. In order to get useful error messages one needs to run this in julia:

```julia
ENV["IJULIA_DEBUG"]=true
using Pkg
Pkg.build("IJulia",verbose=true)
```
Exit julia and run from a terminal

```bash
/home/gher/.julia/conda/3/bin/jupyter notebook
```
where `/home/gher` is my home directory. It should be replaced by your home directory.
On windows, I think the path is rather this:

```
C:\Users\Alexander Barth\.julia\conda\3\Scripts\jupyter-notebook.exe
```

In my tests, this gives a lot of messages in the terminal including any error messages. If you manage to get these message, please paste them here. They usually start like this:

```
I 10:24:59.950 NotebookApp] Serving notebooks from local directory: /home/gher
[I 10:24:59.950 NotebookApp] The Jupyter Notebook is running at:
[I 10:24:59.950 NotebookApp] http://localhost:8888/?token=47dc9c59ebfae58462b7af8e8b19ffb67386d599cd24aefc
[I 10:24:59.950 NotebookApp]  or http://127.0.0.1:8888/?token=47dc9c59ebfae58462b7af8e8b19ffb67386d599cd24aefc
[I 10:24:59.950 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:25:00.086 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/gher/.local/share/jupyter/runtime/nbserver-12281-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=47dc9c59ebfae58462b7af8e8b19ffb67386d599cd24aefc
     or http://127.0.0.1:8888/?token=47dc9c59ebfae58462b7af8e8b19ffb67386d599cd24aefc
[I 10:25:11.442 NotebookApp] Creating new notebook in 
[I 10:25:13.406 NotebookApp] Kernel started: 4282d676-87e8-46ee-b968-af5f2bf8d4e8
PROFILE = Dict{String,Any}("key" => "2f457d6d-60a465c796b9475dc1561b3c","transport" => "tcp","signature_scheme" => "hmac-sha256","shell_port" => 47989,"hb_port" => 53427,"control_port" => 58599,"ip" => "127.0.0.1","stdin_port" => 45825,"iopub_port" => 59595,"kernel_name" => "julia-1.4")
10:25:21(): SENDING IPython Msg [ idents status ] {
  parent_header = Dict("username" => "jlkernel","session" => "UUID(\"82989848-a65b-4d0a-a71e-dbcfc07b1c80\")"),
  header = Dict{String,Any}("msg_id" => "UUID(\"bfc49cc7-0991-4821-882c-8df9dbdcc3be\")","msg_type" => "status","username" => "jlkernel","date" => 2020-05-08T10:25:20.89,"version" => "5.3","session" => "UUID(\"82989848-a65b-4d0a-a71e-dbcfc07b1c80\")"),
  metadata = Dict{String,Any}(),
  content = Dict("execution_state" => "starting")
}
Starting kernel event loops.
```

**Comment by nicolascouetard** [comment]
> /home/ncouetard/.julia/conda/3/bin/jupyter notebook --debug assim_exercise.ipynb

**The typo solved the problem, it works perfectly now!** Thanks a lot.

**Comment by mutiarizqydiani** [comment]
@Alexander-Barth I'm trying to follow the steps that you tell Nicolas. So here what I got

For this part:
`ENV["IJULIA_DEBUG"]=true
using Pkg
Pkg.build("IJulia",verbose=true)`

I got the result:
`julia> ENV["IJULIA_DEBUG"]=true
true

julia> using Pkg

julia> Pkg.build("IJulia",verbose=true)
   Building Conda ─→ `C:\Users\Mutia\.julia\packages\Conda\3rPhK\deps\build.log`
   Building IJulia → `C:\Users\Mutia\.julia\packages\IJulia\DrVMH\deps\build.log`
[ Info: Installing Julia kernelspec in C:\Users\Mutia\AppData\Roaming\jupyter\kernels\julia-1.4`

Then I proceed to this part:
`jupyter-notebook  --debug assim_exercise.ipynb`

And I got:
julia> jupyter-notebook --debug assim_exercise.ipynb
ERROR: syntax: invalid operator "--"
Stacktrace:
 [1] top-level scope at REPL[4]:0

OR
`/full/path/to/jupyter-notebook   --debug assim_exercise.ipynb`

I got:
`julia> C:\Users\Mutia\.julia\conda\3\Scripts\jupyter-notebook --debug assim_exercise.ipynb
ERROR: syntax: "\" is not a unary operator
Stacktrace:
 [1] top-level scope at REPL[4]:0`

**Comment by Alexander-Barth** [comment]
@mutiarizqydiani , there are some command that you need to type in julia. This for instance (as you probably did):
```julia
ENV["IJULIA_DEBUG"]=true
using Pkg
Pkg.build("IJulia",verbose=true)
```

And some commands in a cmd window terminal which you can access as described here:
https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/
In this terminal you need to type these commands

```
cd C:\Users\Mutia\path\with\the\notebooks
C:\Users\Mutia\.julia\packages\Conda\3\Scripts\jupyter-notebook --debug assim_exercise.ipynb
```

where you need to replace `path\with\the\notebooks` with the folder containing the notebooks. If you have a problem locating the path of the folder containing the notebooks you can also run:

```
cd C:\Users\Mutia\
C:\Users\Mutia\.julia\packages\Conda\3\Scripts\jupyter-notebook --debug 
```
The should open a browser window with a file manager. And then navigate into the folder with the notebooks.
If this does not work, you should be able to see the error message in the cmd window terminal why it does not work.

In a windows cmd terminal, can you also show me the output of the following command:

```
echo %PATH%
```
and send me the output?

**Comment by Alexander-Barth** [comment]
@nicolascouetard  Thanks a lot for confirming that it now works!

**Comment by mutiarizqydiani** [comment]
> @mutiarizqydiani , there are some command that you need to type in julia. This for instance (as you probably did):
> 
> ```julia
> ENV["IJULIA_DEBUG"]=true
> using Pkg
> Pkg.build("IJulia",verbose=true)
> ```
> 
> And some commands in a cmd window terminal which you can access as described here:
> https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/
> In this terminal you need to type these commands
> 
> ```
> cd C:\Users\Mutia\path\with\the\notebooks
> C:\Users\Mutia\.julia\packages\Conda\3\Scripts\jupyter-notebook --debug assim_exercise.ipynb
> ```
> 
> where you need to replace `path\with\the\notebooks` with the folder containing the notebooks. If you have a problem locating the path of the folder containing the notebooks you can also run:
> 
> ```
> cd C:\Users\Mutia\
> C:\Users\Mutia\.julia\packages\Conda\3\Scripts\jupyter-notebook --debug 
> ```
> 
> The should open a browser window with a file manager. And then navigate into the folder with the notebooks.
> If this does not work, you should be able to see the error message in the cmd window terminal why it does not work.
> 
> In a windows cmd terminal, can you also show me the output of the following command:
> 
> ```
> echo %PATH%
> ```
> 
> and send me the output?

@Alexander-Barth 

This is the error message that I got

> C:\Users\Mutia>C:\Users\Mutia\.julia\conda\3\Scripts\jupyter-notebook --debug

Traceback (most recent call last):
  File "C:\Users\Mutia\.julia\conda\3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

And for

> echo %PATH%

I got this:
> C:\Users\Mutia> echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MATLAB\MATLAB Compiler Runtime\v83\runtime\win64;C:\Users\Mutia\.julia\conda\3\condabin;C:\Users\Mutia\AppData\Local\Microsoft\WindowsApps;

**Comment by Alexander-Barth** [comment]
Concering the error `ImportError: DLL load failed: The specified module could not be found.` I found this link: https://stackoverflow.com/questions/54224969/import-error-while-trying-to-run-jupyter-notebook

So for some users, reinstalling jupyter/IJulia helped. Can you try these commands in Julia?

```julia
using IJulia
IJulia.Conda.rm("pyzmq")
IJulia.Conda.add("jupyter")
```

Or if this easier for you, you can also remove the folder `C:\Users\Mutia\.julia` (this removes all julia packages, but keeps Julia installed) and reinstall the Julia packages (IJulia, PyPlot...)

Then can you try the command again in the windows cmd terminal to see if the error disappears?

```
C:\Users\Mutia>C:\Users\Mutia.julia\conda\3\Scripts\jupyter-notebook --debug
```

**Comment by mutiarizqydiani** [comment]
> Concering the error `ImportError: DLL load failed: The specified module could not be found.` I found this link: https://stackoverflow.com/questions/54224969/import-error-while-trying-to-run-jupyter-notebook
> 
> So for some users, reinstalling jupyter/IJulia helped. Can you try these commands in Julia?
> 
> ```julia
> using IJulia
> IJulia.Conda.rm("pyzmq")
> IJulia.Conda.add("jupyter")
> ```
> 
> Or if this easier for you, you can also remove the folder `C:\Users\Mutia\.julia` (this removes all julia packages, but keeps Julia installed) and reinstall the Julia packages (IJulia, PyPlot...)
> 
> Then can you try the command again in the windows cmd terminal to see if the error disappears?
> 
> ```
> C:\Users\Mutia>C:\Users\Mutia.julia\conda\3\Scripts\jupyter-notebook --debug
> ```

I'm reinstalling Julia and now in the middle of installing the packages, it seems like it freeze. It looks like this and hasn't change in the past 1 hour.

> julia> using Pkg

julia> Pkg.add(PackageSpec(url="https://github.com/Alexander-Barth/GeoMapping.jl",rev="master"))
    Cloning git-repo `https://github.com/Alexander-Barth/GeoMapping.jl`
   Updating git-repo `https://github.com/Alexander-Barth/GeoMapping.jl`
  Resolving package versions...
    Cloning default registries into `C:\Users\Mutia\.julia`
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
    Fetching: [===========>                             ]  25.9 %

**Comment by Alexander-Barth** [comment]
`Fetching` means that it is downloading data from https://github.com/JuliaRegistries/General.git . Could it be a network problem on your side or from github?

**Comment by mutiarizqydiani** [comment]
> `Fetching` means that it is downloading data from https://github.com/JuliaRegistries/General.git . Could it be a network problem on your side or from github?

Ah yes, I'm sorry. The problem was from my network. I'm done reinstalling Julia and its packages. I also tried this before test the path with command prompt, and it was fine. 

`using` IJulia
IJulia.Conda.rm("pyzmq")
IJulia.Conda.add("jupyter")`

Then I test the path

> C:\Users\Mutia>C:\Users\Mutia\.julia\conda\3\Scripts\jupyter-notebook --debug

And it shows the same error message, like this:

> Traceback (most recent call last):
  File "C:\Users\Mutia\.julia\conda\3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Mutia\.julia\conda\3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

**Comment by NienkevandeLoosdrecht** [comment]
> I use Ubuntu 20.04 too (gnome version). In the julia command line can you run the following (https://github.com/JuliaLang/IJulia.jl#debugging-ijulia-problems):
> 
> ```
> ENV["IJULIA_DEBUG"]=true
> using Pkg
> Pkg.build("IJulia",verbose=true)
> ```
> 
> Can you paste the output of this previous command?
> 
julia> ENV["IJULIA_DEBUG"]=true
true

julia> using Pkg

julia> Pkg.build("IJulia",verbose=true)
   Building Conda ─→ `~/.julia/packages/Conda/3rPhK/deps/build.log`
   Building IJulia → `~/.julia/packages/IJulia/DrVMH/deps/build.log`
[ Info: Installing Julia kernelspec in /Users/nienkevandeloosdrecht/Library/Jupyter/kernels/julia-1.4



> Then can you start `jupyter-notebook` from the terminal
> 
> ```shell
> jupyter-notebook  --debug assim_exercise.ipynb
> ```
> (base) Nienkes-MacBook-Pro:~ nienkevandeloosdrecht$ jupyter-notebook  --debug assim_exercise.ipynb
[C 11:05:01.407 NotebookApp] No such file or directory: /Users/nienkevandeloosdrecht/assim_exercise.ipynb
[D 11:05:01.407 NotebookApp] Exiting application: jupyter-notebook

> or
> 
> ```shell
> /full/path/to/jupyter-notebook   --debug assim_exercise.ipynb
> ```
(base) Nienkes-MacBook-Pro:~ nienkevandeloosdrecht$ /Users/nienkevandeloosdrecht/opt/anaconda3/pkgs/notebook-6.0.3-py37_0/bin/jupyter-notebook --debug assim_exercise.ipynb
-bash: /Users/nienkevandeloosdrecht/opt/anaconda3/pkgs/notebook-6.0.3-py37_0/bin/jupyter-notebook: /opt/anaconda1anaconda2anaconda3/bin/python: bad interpreter: No such file or directory



> 
> (by replacing `/full/path/to/` with the directory containing `jupyter-notebook`).
> 
> There might be some helpful error message in the terminal why the kernel is crashing.

This is what I got but I don't fully understand what I should do next?

**Comment by Alexander-Barth** [comment]
@NienkevandeLoosdrecht Thank you for your test, but this error message is quite problematic `bad interpreter: No such file or directory` . For some reasons Ijulia and anaconda is interfering with each other and you are unable to use IJulia. 

@NienkevandeLoosdrecht, @ mutiarizqydiani : for the lecture I suggest you to use the binder service instead:

https://github.com/Alexander-Barth/HF-radar-assim-exercise#using-binder
