### ISSUE TITLE
"No such file or directory"

### ISSUE THREAD

**Issue by marinecourteille** [Alexander-Barth/HF-radar-assim-caen#2]
Hi!
I downloaded and installed Julia on my computer under Windows 64-bit with apparently no problem.
When I try to install Julia packages in the Julia window, I get this message:
"ERROR: SystemError: opening file "C:\\Users\\Marine\\.julia\\registries\\General\\Registry.toml": No such file or directory" and then 33 lines below. I have this for each command line.
Do I need to install anything else before trying to install packages? Do you have any idea to solve this error? It's the first step in the guidelines after installing Julia, so I don't understand why it doesn't work.
Thank you in advance,
Marine Courteille

**Comment by Alexander-Barth** [comment]
Maybe there was a problem when julia generated the list of known packages (called "General").
Can you delete the folder `C:\Users\Marine\.julia` and try again?
Are you running an anti-virus software (like Windows Defender,...) ?

In the past some students had a problem with the anti-virus software interfering with julia. It helped to disabled the anti-virus while adding the packages.

**Comment by Alexander-Barth** [comment]
Here is somebody with apparently the same problem and removing the folder resolved the problem for him:

https://discourse.julialang.org/t/registry-toml-missing/24152

Let's hope that it works for you too!

**Comment by marinecourteille** [comment]
I deleted the folder .julia and tried again and it worked!
Thank you, it was so simple but I didn't think about it.

**Comment by Alexander-Barth** [comment]
Thanks Marine for your feedback! Great to know it worked now!
